name: hw2_env
dependencies: 
  - python=3.7
  - pip
  - pip: 
    - torch==1.5.0
    - torchvision==0.6.0
    - Pillow==8.1.0
    - numpy==1.20.1
    - pandas==1.2.2
    - seaborn==0.9.0
    - matplotlib==3.4.1
